services:
  mongodb:
    image: mongo:7
    container_name: mini-stock-mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: mini-stock-redis
    ports:
      - '6379:6379'

  rabbitmq:
    image: rabbitmq:3-management
    container_name: mini-stock-rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'

volumes:
  mongo_data:
